### ISSUE TITLE
Вишневский Георгий Лаба 1

### ISSUE THREAD

**Issue by Victem** [Victem/web-progr#15]

**Comment by Victem** [comment]
Хмм... Новая конституция замиксованная с цитатами, человека "заложившего ядерную бомбу под основами русской государственности" К-К-Комбо. Защитано.

Зачем ты дивы с тасками комментируешь не понятно, но ладно. 

Форма, ты отправляешь файл, но не указываешь атрибут (сам найди какой), в итоге данные отправятся а файл нет.

https://github.com/GVishnevskiy/web-progr/blob/georgiy-vishnevskiy/src/index.html#L215
Косяк, но н катастрофа.

https://github.com/GVishnevskiy/web-progr/blob/georgiy-vishnevskiy/src/index.html#L233
Вот не уверен, возможно и прокатит, но считаю, что в option нужно указывать value

https://github.com/GVishnevskiy/web-progr/blob/georgiy-vishnevskiy/src/index.html#L250  этого не писал, но рекомендуется радиокнопкам один вариант помечать атрибутом checked.

**Comment by GVishnevskiy** [comment]
исправил
