### ISSUE TITLE
Михейко Виктория Лаба 1

### ISSUE THREAD

**Issue by Victem** [Victem/web-progr#19]

**Comment by ViktoriaMi** [comment]
Проверьте

**Comment by Victem** [comment]
Со списками косячок, посмотри пример. https://webref.ru/layout/html5-css3/list/nested.
В обновленной версии еще задания подъехали по таблицам фреймам и формам.

**Comment by ViktoriaMi** [comment]
А в чем именно ошибка? Там где семестры или термины?24.04.2020, 22:11, "Andrew Lobov" <notifications@github.com>:
Со списками косячок, посмотри пример. https://webref.ru/layout/html5-css3/list/nested.
В обновленной версии еще задания подъехали по таблицам фреймам и формам.

**Comment by Victem** [comment]
И в семестрах и в терминах. 
В терминах вообще жуть какая-то посмотрите внимательней разметку в примере в Readme.

**Comment by ViktoriaMi** [comment]
Так ведь в семестрах сказано, там, где номер семестра - нумерованный список, дисциплина - маркированный. Не понимаю, что именно в семестрах не так. Или нужно вложенные нумерованные списки сделать?25.04.2020, 11:47, "Andrew Lobov" <notifications@github.com>:
И в семестрах и в терминах.
В терминах вообще жуть какая-то посмотрите внимательней разметку в примере в Readme.

**Comment by Victem** [comment]
Правильно. В типах списка вы все поняли правильно. ошибка именно в разметке. Тэги не так расставили. Еще раз сравните ваше решение с примером который я прислал.

**Comment by Victem** [comment]
Ты его победила
